# Generated by Django 5.2.6 on 2025-09-24 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('account_number', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('balance', models.IntegerField(default=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('time', models.DateField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=20)),
                ('transactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.account')),
            ],
        ),
    ]
