# Generated by Django 5.2.6 on 2025-09-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_history',
            old_name='transactions',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='transaction_history',
            old_name='time',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
